#include<iostream>
using namespace std;

int main(){
    //  int marks[4] = {0,2,3,4};
    //  cout<<"These are amrks"<<endl;
    //  cout<<marks[0]<<endl;
    //  cout<<marks[1]<<endl;
    //  cout<<marks[2]<<endl;
    //  cout<<marks[3]<<endl;
  int marks[4];
  marks[0] =0;
  marks[1]=1;
  marks[2]=2;
  marks[3]=3;
  marks[4]=4;
  cout<<"marks[0] is "<<marks[0]<<endl;
  cout<<"marks[1] is "<<marks[1]<<endl;
  cout<<"marks[2] is "<<marks[2]<<endl;
  cout<<"marks[3] is "<<marks[3]<<endl;

     

    return 0;
}